### ISSUE TITLE
smallweb version upgrade - upgrade from source ?

### ISSUE THREAD

**Issue by gedw99** [pomdtr/smallweb#19]
Would you be open to this allowing upgrades form source  ?

```sh

smallweb --version
smallweb version dev

smallweb version upgrade
You're compiling from source. Please update manually.

```

**Comment by pomdtr** [comment]
What would you expect to happen there ?

Would the new release replace the dev binary ?

**Comment by pomdtr** [comment]
Closing this, as I don't think running smallweb from source should be a common experience for users.
