### ISSUE TITLE
Can't signup

### ISSUE THREAD

**Issue by nbbaier** [pomdtr/smallweb#2]
After entering my email and desired username using `smallweb auth signup` I get `Error: failed to sign up`

**Comment by pomdtr** [comment]
Sry about that, I'll take a look tomorrow!

**Comment by pomdtr** [comment]
Looks like I need to setup my own domain on resend (or just use val.town to send emails).

**Comment by nbbaier** [comment]
What are you using to host the server?

**Comment by pomdtr** [comment]
Should be fixed in `v0.1.4` (I switched to /v1/email).

I use a single fly.io VM for the hosting.
