### ISSUE TITLE
valtown sse example almost works, but doesn't force utf-8

### ISSUE THREAD

**Issue by tarasglek** [pomdtr/smallweb#22]
valtown: https://maxm-robpikeio.web.val.run 

smallweb:
```ts
import * as lib from "https://esm.town/v/maxm/robPikeIO?v=11";

export default {
  fetch: lib.default,
};
```

**Comment by tarasglek** [comment]
Though maybe valtown is in the wrong here. Adding ;charset=UTF-8 to content-type works

**Comment by pomdtr** [comment]
> Though maybe valtown is in the wrong here. Adding ;charset=UTF-8 to content-type works

Yeah that was my conclusion too. I do not want to mess with headers from smallweb
